// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB0y7EGVm9_IIeAlNQ31ar7iBJwF-rpoo',
    appId: '1:979193032093:web:8e010733de296c134ad374',
    messagingSenderId: '979193032093',
    projectId: 'chat-app-e4acf',
    authDomain: 'chat-app-e4acf.firebaseapp.com',
    storageBucket: 'chat-app-e4acf.appspot.com',
    measurementId: 'G-1MB5PH2N60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdWp_ZvMTzYtOc_60GdZSN6tfF3d7QQlM',
    appId: '1:979193032093:android:6e49acbb6b1397ad4ad374',
    messagingSenderId: '979193032093',
    projectId: 'chat-app-e4acf',
    storageBucket: 'chat-app-e4acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYzy1_UovGiuGA1QVgjQxZGv8j2De7kt4',
    appId: '1:979193032093:ios:5b92b022f3b5cbf74ad374',
    messagingSenderId: '979193032093',
    projectId: 'chat-app-e4acf',
    storageBucket: 'chat-app-e4acf.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYzy1_UovGiuGA1QVgjQxZGv8j2De7kt4',
    appId: '1:979193032093:ios:5b92b022f3b5cbf74ad374',
    messagingSenderId: '979193032093',
    projectId: 'chat-app-e4acf',
    storageBucket: 'chat-app-e4acf.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB0y7EGVm9_IIeAlNQ31ar7iBJwF-rpoo',
    appId: '1:979193032093:web:a52479ae0fbf16094ad374',
    messagingSenderId: '979193032093',
    projectId: 'chat-app-e4acf',
    authDomain: 'chat-app-e4acf.firebaseapp.com',
    storageBucket: 'chat-app-e4acf.appspot.com',
    measurementId: 'G-BTN2G0M8GJ',
  );
}
